### ISSUE TITLE
bug太多，需要修复

### ISSUE THREAD

**Issue by RondaHe** [Joker-King/TextUtil#1]
朋友圈没数据，表情发送不出去，表情上滑动崩溃等

**Comment by 0xhellohaley** [comment]
很抱歉给你添麻烦了，朋友圈没数据是因为朋友圈的数据我注释掉了，你在控制器中打开即可。
表情发送不出去，我在模拟器4s/5/5s同时7.1和8.3中没有问题，6中发送表情点击确实没反应，我测试修复一下
目前没遇到表情崩溃的问题。
另外，我这个demo,只是写了一种图文混排，相对来说比较简单的原生实现，提供一种思路，主要起到抛砖引玉的作用。

**Comment by 0xhellohaley** [comment]
表情发送不出去的问题，是6上frame的问题。
bottomView = [[UIView alloc] initWithFrame:CGRectMake(0, pageControl.bottom+10, 320, 35)];
改为bottomView = [[UIView alloc] initWithFrame:CGRectMake(0, pageControl.bottom+10, kWidth, 35)];
表情视图的位置还有点问题，我就不改啦~

**Comment by RondaHe** [comment]
嗯，好的，谢谢及时回复。我最近在做社交软件，想各种参考一下，谢谢提供的demo。可以关闭这个issue了
