### ISSUE TITLE
我试着做了个table,但是很卡,不知可有优化方案呢

### ISSUE THREAD

**Issue by chengxianghe** [Joker-King/TextUtil#3]
我已经在model缓存了cell高度, 而且只是在请求回来之后匹配一次富文本,计算一次高度,但是还是很卡,在cell内部, 我是直接把attributestring 赋值给了textView的attributestring的.这里不知道该怎么优化,特来求助

**Comment by 0xhellohaley** [comment]
最好用调试工具调试一下，在哪个地方用了超时操作。用attributestring肯定是没问题的。
